<a href="https://colab.research.google.com/github/ShrijanMaharjan/MachineLearning/blob/main/Comparispn/Introduvtion-to-MachineLearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to Numpy
What we will cover?
- Creating arrays ✅
- Multidimensional array ✅
- Randomly Generated Arrays
- Element wise operation
- Summarizing Operations

### Single Dimensional Array

In [2]:
import numpy as np

In [ ]:
#create an array wuth all the elements to be zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
#create an array of size 10 with all elements 3
np.full(10, 3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [ ]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [ ]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
#create an array with evenly spaced numbers within a specified range
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

### Multi Dimensional Array

In [ ]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
a = np.array((
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
))
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a[0, 1] = 20
a

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [ ]:
#a[2:3] = 1
a

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [ ]:
#a[:, 2] = 2
a

array([[ 1, 20,  2],
       [ 4,  5,  2],
       [ 1,  1,  2]])

In [ ]:
np.full((3,3),10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

### Randomly Generated Arrays

- NumPy can create arrays filled with random numbers
- To ensure the reproducibility, you can set a seed using ```np.random.seed()```. It will generate the exact same random numbers for each executions.
- If you remove or change the seed values, the sequence of random numbers will be changed.

In [ ]:
np.random.rand(5)

array([0.50253306, 0.68666708, 0.25367965, 0.55474086, 0.62493084])

In [ ]:
np.random.seed(5)
np.random.rand(5)



array([0.22199317, 0.87073231, 0.20671916, 0.91861091, 0.48841119])

In [ ]:
np.random.randn(5, 5)

array([[-0.84408314,  0.74820756,  0.30623359,  0.80136392,  0.9884962 ],
       [ 1.01137769,  0.76252192, -0.06984125,  0.26233548, -0.13822085],
       [-0.22134993, -0.60793652, -1.241353  ,  1.33224618, -0.21379391],
       [-0.15395897, -0.08313719, -0.2586124 , -0.16073609, -0.46921573],
       [ 0.4379501 ,  0.52294784, -0.50634964,  0.3660525 ,  1.27085002]])

In [ ]:
np.random.randn(5, 5)

array([[ 0.07457166,  0.48855886,  0.8920556 , -0.54087096,  0.1899391 ],
       [-0.92133518,  2.13266765, -0.38056226, -2.13080095,  0.69665506],
       [-0.10038772,  0.96878656,  1.84190347, -1.12735176,  0.56123214],
       [ 0.033073  , -0.01692838,  1.48055315,  0.47309345, -1.31421292],
       [ 0.83352633,  0.80978418, -1.77977907, -1.73799642, -1.06284807]])

In [3]:
np.random.randint(low=0, high=100, size=(5,2))

array([[80, 76],
       [79, 34],
       [78, 93],
       [41, 38],
       [14,  3]])

### Element wise operation on entire arrays element by element

In [5]:
import numpy as np
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [7]:
b= (10+(a*2))
b

array([10, 12, 14, 16, 18])

In [9]:
#comparison operations
a

array([0, 1, 2, 3, 4])

In [11]:
a >= 2

array([False, False,  True,  True,  True])

In [12]:
a > b

array([False, False, False, False, False])

In [13]:
#summarizing of the data
#Numpy provides functions for summarizing array data
a



array([0, 1, 2, 3, 4])

In [14]:
a.std()

1.4142135623730951

In [15]:
a.min()

0

In [16]:
a.max()

4

In [17]:
a.sum()

10