<a href="https://colab.research.google.com/github/ShrijanMaharjan/MachineLearning/blob/main/Introduvtion-to-MachineLearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to Numpy
What we will cover?
- Creating arrays ✅
- Multidimensional array ✅
- Randomly Generated Arrays
- Element wise operation
- Summarizing Operations

### Single Dimensional Array

In [63]:
import numpy as np

In [3]:
#create an array wuth all the elements to be zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [6]:
#create an array of size 10 with all elements 3
np.full(10, 3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [7]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [9]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [10]:
#create an array with evenly spaced numbers within a specified range
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

### Multi Dimensional Array

In [11]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
a = np.array((
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
))
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
a[0, 1] = 20
a

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [19]:
a[2:3] = 1
a

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [20]:
a[:, 2] = 2
a

array([[ 1, 20,  2],
       [ 4,  5,  2],
       [ 1,  1,  2]])

In [25]:
np.full((3,3),10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

### Randomly Generated Arrays

- NumPy can create arrays filled with random numbers
- To ensure the reproducibility, you can set a seed using ```np.random.seed()```. It will generate the exact same random numbers for each executions.
- If you remove or change the seed values, the sequence of random numbers will be changed.

In [54]:
np.random.rand(5)

array([0.50253306, 0.68666708, 0.25367965, 0.55474086, 0.62493084])

In [56]:
np.random.seed(5)
np.random.rand(5)



array([0.22199317, 0.87073231, 0.20671916, 0.91861091, 0.48841119])

In [69]:
np.random.randn(5, 5)

array([[-0.84408314,  0.74820756,  0.30623359,  0.80136392,  0.9884962 ],
       [ 1.01137769,  0.76252192, -0.06984125,  0.26233548, -0.13822085],
       [-0.22134993, -0.60793652, -1.241353  ,  1.33224618, -0.21379391],
       [-0.15395897, -0.08313719, -0.2586124 , -0.16073609, -0.46921573],
       [ 0.4379501 ,  0.52294784, -0.50634964,  0.3660525 ,  1.27085002]])

In [74]:
np.random.randint(low=0, high=100, size=(5,2))

TypeError: 'tuple' object is not callable